openapi: 3.1.0
info:
  title: Lecture Manager API
  description: API for managing lecture content, transcripts, videos, and flashcards
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development server

tags:
  - name: Health Check
    description: Server health checks
  - name: Lecture
    description: Operations related to lectures

paths:
  /:
    get:
      summary: Health Check
      description: Check if the server is running
      tags:
        - Health Check
      responses:
        "200":
          description: Server is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Server is up!

  /lecture/{id}:
    get:
      summary: Get lecture details
      description: Retrieve details for a specific lecture by ID
      tags:
        - Lecture
      parameters:
        - name: id
          in: path
          required: true
          description: Unique identifier of the lecture
          schema:
            type: string
      responses:
        "200":
          description: Lecture details retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lecture"
        "404":
          description: Lecture not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /lecture/transcript:
    post:
      summary: Upload lecture transcript
      description: Upload a transcript file for a lecture
      tags:
        - Lecture
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The transcript file (text format)
      responses:
        "200":
          description: Transcript uploaded successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lecture"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /lecture/video:
    post:
      summary: Upload lecture video
      description: Upload a video file for a lecture
      tags:
        - Lecture
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The video file
      responses:
        "200":
          description: Video uploaded successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Lecture"
        "400":
          description: Bad request - video file is required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /lecture/flashcard:
    post:
      summary: Create flashcard
      description: Create a new flashcard based on selected text from a lecture section
      tags:
        - Lecture
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - sectionId
                - text
              properties:
                sectionId:
                  type: string
                  description: ID of the lecture section
                text:
                  type: string
                  description: Selected text to create a flashcard from
            example:
              sectionId: "section123"
              text: "The mitochondria is the powerhouse of the cell"
      responses:
        "200":
          description: Flashcard created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Flashcard"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Lecture:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the lecture
        title:
          type: string
          description: Title of the lecture
        transcript:
          type: string
          description: Full text transcript of the lecture
        sections:
          type: array
          description: Lecture content broken into sections
          items:
            type: object
            properties:
              id:
                type: string
              content:
                type: string
              timestamp:
                type: number
                description: Timestamp in the video (if available)
        flashcards:
          type: array
          description: Flashcards generated from the lecture
          items:
            $ref: "#/components/schemas/Flashcard"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Flashcard:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the flashcard
        question:
          type: string
          description: The question side of the flashcard
        answer:
          type: string
          description: The answer side of the flashcard
        sectionId:
          type: string
          description: ID of the lecture section this flashcard relates to
        lectureId:
          type: string
          description: ID of the lecture this flashcard belongs to

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
